apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: yonatan96/walmart-home-assignment:latest  # Replace with your app's Docker image
        ports:
        - containerPort: 3000  # Replace if your app uses a different port
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        - name: MONGO_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MONGO_CONNECTION_URL

